on:
  release:
    types: [published]

name: Build release binaries

jobs:
  build-binaries:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Build binary
        run: |
          binary <- devtools::build(binary = TRUE)
          file.copy(binary, "CNValidatron.zip")
        shell: Rscript {0}
      
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: CNValidatron.zip